version: '3'

services:
  mysql:
    image: mysql:5.6
    networks:
      - mysql
    environment:
      MYSQL_DATABASE: 'shapes'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3360:3306'
    # expose:
    #   - '3360'
    tty: true
    stdin_open: true
  
networks:
  mysql:
    driver: bridge